### ISSUE TITLE
3D Image Volume Capability

### ISSUE THREAD

**Issue by jameybrowning** [Ipsedo/MARLClassification#1]
Are there plans to adapt this code for 3D image volume data? I see that there is a default training argument for dim=2, but when I load a 3D grayscale image (shape = (40,320,320), and set dim = 3 and nb_actions=6, the code throws and error on the return of ./environment/observation.py.

**Comment by Ipsedo** [comment]
The support of other dimensions than 2D is only available partially. If you send me a 3D image dataset I'll enjoy implementing it.

**Comment by jameybrowning** [comment]
Thank you for the reply. I adapted your code to 3D and tested on the Rijeka ACL MRI binary classification dataset (right knee only) http://www.riteh.uniri.hr/~istajduh/projects/kneeMRI/, but the results get stuck at precision < 50% and recall at exactly 50%. I rescaled the images to 320x320x40, set f (ROI size) to 24x24x24, and expanded the CNN encoder to three 3D conv layers of 16,32,and 64 layers. 

I'd be curious to see if you can get any interesting results from this public 3D dataset - there are many points in my adaptation of your code where I may have made a critical error. MARL Classification is a neat idea and it would be interesting to see if it can be used for something beyond MNIST. I think the Rijeka dataset is a good start because, like MNIST, the pertinent visual cues have consistent relative orientations within the image. 

Thanks for sharing your code. I'll keep at it when I have some more free time and see if I can make any progress.

**Comment by Ipsedo** [comment]
N-D adaptation is theorically functional !
Unfortunately the kneeMRI dataset does not have enough observations to get a convergence...

I close the issue but feel free to re-open it if the N-D generalization isn't working properly
