### ISSUE TITLE
Is the code improved based on the paper?

### ISSUE THREAD

**Issue by tjnkyqcy** [Ipsedo/MARLClassification#10]
Also, is your code based on the paper with new modifications, the code involves A2C-like strategies that don't seem to be presented in the paper, which is a bit unclear to me. I hope you can help.

**Comment by Ipsedo** [comment]
No the actor critic part is an enhancement. In the original paper they use policy reinforce algorithm.
But results were better with actor critic algorithm.

**Comment by Ipsedo** [comment]
If you want the original version you can look at original-paper branch (but I don't remember if it was working).
With no update on your side can I consider it as resolved and close the issue?

**Comment by tjnkyqcy** [comment]
Where is the ORIGINAL-PAPER branch you mentioned, sorry I couldn't find it, could you provide me with a link, thanks.

**Comment by Ipsedo** [comment]
https://github.com/Ipsedo/MARLClassification/tree/original-paper
