### ISSUE TITLE
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.

### ISSUE THREAD

**Issue by CharishmaPasala** [Ipsedo/MARLClassification#3]
While running download_minist.sh file I am facing the following error,
Download MNIST png from Kaggle
Traceback (most recent call last):
  File "/opt/conda/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/opt/conda/lib/python3.7/site-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/opt/conda/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 166, in authenticate
    self.config_file, self.config_dir))
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.
Extract mnistzip.zip
unzip:  cannot find or open /kaggle/working/MARLClassification/resources/downloaded/mnistzip.zip, /kaggle/working/MARLClassification/resources/downloaded/mnistzip.zip.zip or /kaggle/working/MARLClassification/resources/downloaded/mnistzip.zip.ZIP.
Create all_png folder
mkdir: cannot create directory ‘/kaggle/working/MARLClassification/resources/downloaded/mnist_png/all_png’: No such file or directory
Copy train img to all_png folder
cp: cannot stat '/kaggle/working/MARLClassification/resources/downloaded/mnist_png/train/*': No such file or directory
Copy eval img to all_png folder
cp: cannot stat '/kaggle/working/MARLClassification/resources/downloaded/mnist_png/valid/*': No such file or directory

**Comment by Ipsedo** [comment]
The error message is clear :
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.

You must put your Kaggle api key in .kaggle folder in order to use kaggle command.

I close the issue.

**Comment by Ipsedo** [comment]
https://www.kaggle.com/docs/api
