### ISSUE TITLE
Skin Cancer Dataset link is not working

### ISSUE THREAD

**Issue by saptab** [Ipsedo/MARLClassification#7]
Hi, the skin cancer dataset link provided is not working https://drive.google.com/drive/folders/17g6zFSbCNXTV3VaDKop73W7Cn-NJlTO7?usp=sharing. 

please share the correct link

**Comment by Ipsedo** [comment]
Where did you get this link?
It is not integrated to my repo

**Comment by Ipsedo** [comment]
It was for an old issue, I don't manage this Google drive link. You must contact the guy from this issue https://github.com/Ipsedo/MARLClassification/issues/4
Nevertheless it is out of scope of this repository code, please do not create issue for this...
