### ISSUE TITLE
run test

### ISSUE THREAD

**Issue by tjnkyqcy** [Ipsedo/MARLClassification#9]
May I know which file path should be filled in the "--state-dict-path" file path in the settings needed to run test?

**Comment by Ipsedo** [comment]
You need to put the PyTorch model state dict for this option which can be found in the training output folder (the .pt file). 
You also need to put the json file of your trained model, this one contains all the hyper-parameters needed to create the model (also present in your training output folder).

**Comment by tjnkyqcy** [comment]
Thanks so much for the tip, I've been able to run test without any problems!

**Comment by Ipsedo** [comment]
You're welcome.
If it's okay for your side you can close the issue ;)
